### ISSUE TITLE
test new  torch.distributed 

### ISSUE THREAD

**Issue by martinjaggi** [mlbench/mlbench-core#15]
from pytorch 1.0 there is now a newly implemented ` torch.distributed` which is asynchronous. we should compare it to the existing code we have even in the synchronous model

**Comment by Panaetius** [comment]
New JIT might also be interesting, to check the speedup over regular python code

**Comment by Panaetius** [comment]
There's currently an issue building from source with official nvidia images, the workaround mentioned in https://github.com/pytorch/pytorch/issues/14930 is used (Use CuDNN 7.3.0 instead of 7.4.1)

**Comment by LucianaMarques** [comment]
As discussed in #19, I'd like to take a look at this :)

**Comment by Panaetius** [comment]
Great, thank you :) 

I've added you as a collaborator so I can assign this issue to you (Sadly, Github still doesn't allow assigning issues to users in general)

**Comment by LucianaMarques** [comment]
> Great, thank you :)
> 
> I've added you as a collaborator so I can assign this issue to you (Sadly, Github still doesn't allow assigning issues to users in general)

Thank you very much! I just accepted the invitation!

**Comment by LucianaMarques** [comment]
> from pytorch 1.0 there is now a newly implemented ` torch.distributed` which is asynchronous. we should compare it to the existing code we have even in the synchronous model

I assume it's C10D library, correct? I'm researching about how to use it, but found it a little confusing.

> New JIT might also be interesting, to check the speedup over regular python code

I think this would be interesting to do. I found documentation on this in [here](https://pytorch.org/docs/stable/jit.html?highlight=jit#) and would like to create a separate class for test it. Is it ok? What design patterns in this case should be followed?

**Comment by martinjaggi** [comment]
this issue has outdated context by now. it can be closed once the newer #75 is solved
