### ISSUE TITLE
Add metrics logging for Tensorflow

### ISSUE THREAD

**Issue by Panaetius** [mlbench/mlbench-core#19]
Currently, tensorflow TrainValidation does not log metrics to the dashboard.

Add functionality to do this, akin to the LogMetrics class for pytorch (This class should be framework agnostic anyways?)

**Comment by LucianaMarques** [comment]
Hey!

I would like to give this a try, is it ok?

**Comment by Panaetius** [comment]
Oh I'm very sorry, I forgot to assign myself to this issue. I already added this locally last week, but still need to test it before pushing. :disappointed: 

If you want to try something a little more challenging, but still pretty straight-forward, there's #15  which is about creating a new benchmark image that uses https://pytorch.org/docs/stable/nn.html#torch.nn.parallel.DistributedDataParallel instead of using `torch.distributed` directly. There's a pytorch 1.0 base image available in the branch here https://github.com/mlbench/mlbench-benchmarks/blob/feature/pytorch-1.0-distributed/pytorch/base/Dockerfile , would be cool to have a new benchmark using that, based on this existing benchmark: https://github.com/mlbench/mlbench-benchmarks/tree/develop/pytorch/imagerecognition/openmpi-cifar10-resnet20-all-reduce

**Comment by LucianaMarques** [comment]
> Oh I'm very sorry, I forgot to assign myself to this issue. I already added this locally last week, but still need to test it before pushing. disappointed

No problem, let me know if I can help you with that :)

> If you want to try something a little more challenging, but still pretty straight-forward, there's #15 which is about creating a new benchmark image that uses https://pytorch.org/docs/stable/nn.html#torch.nn.parallel.DistributedDataParallel instead of using `torch.distributed` directly. There's a pytorch 1.0 base image available in the branch here https://github.com/mlbench/mlbench-benchmarks/blob/feature/pytorch-1.0-distributed/pytorch/base/Dockerfile , would be cool to have a new benchmark using that, based on this existing benchmark: https://github.com/mlbench/mlbench-benchmarks/tree/develop/pytorch/imagerecognition/openmpi-cifar10-resnet20-all-reduce

Thank you, I'll take a look at it!

**Comment by Panaetius** [comment]
Fixed with https://github.com/mlbench/mlbench-benchmarks/commit/84e4c5a914593f889601ada46225c796d3fa3135
