### ISSUE TITLE
fails to create kind cluster

### ISSUE THREAD

**Issue by b1ueshad0w** [mlbench/mlbench-core#277]
Command and output:
```
# mlbench create-cluster kind 3 my-cluster /root/mlbench-helm
/usr/local/lib/python3.6/site-packages/tensorflow-1.13.2-py3.6-linux-x86_64.egg/tensorflow/python/framework/dtypes.py:526: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/usr/local/lib/python3.6/site-packages/tensorflow-1.13.2-py3.6-linux-x86_64.egg/tensorflow/python/framework/dtypes.py:527: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/usr/local/lib/python3.6/site-packages/tensorflow-1.13.2-py3.6-linux-x86_64.egg/tensorflow/python/framework/dtypes.py:528: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/usr/local/lib/python3.6/site-packages/tensorflow-1.13.2-py3.6-linux-x86_64.egg/tensorflow/python/framework/dtypes.py:529: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/usr/local/lib/python3.6/site-packages/tensorflow-1.13.2-py3.6-linux-x86_64.egg/tensorflow/python/framework/dtypes.py:530: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/usr/local/lib/python3.6/site-packages/tensorflow-1.13.2-py3.6-linux-x86_64.egg/tensorflow/python/framework/dtypes.py:535: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
Usage: mlbench create-cluster kind [OPTIONS] num-workers RELEASE
Try 'mlbench create-cluster kind --help' for help.

Error: Got unexpected extra argument (/root/mlbench-helm)
```
> `/root/mlbench-helm` is cloned from `https://github.com/mlbench/mlbench-helm.git`, `mlbench` comes from `python3 setup.py install` using the latest `master` branch.

Seems like command `mlbench create-cluster kind` only accpets 2 arguments. 
However this is the error message when I try to pass 2 arguments:
```
# mlbench create-cluster kind 3 my-cluster
Creating cluster my-cluster-3
Usage: mlbench create-cluster kind [OPTIONS] num-workers RELEASE

Error: Failed to create cluster with the following error:
 Error: failed to create cluster: decoding failure: no kind "Cluster" is registered for version "kind.x-k8s.io/v1alpha4" in scheme "pkg/runtime/scheme.go:101"
```

Here's the verson of related tools:
* mlbench: version 2.4.0-dev264
* helm: helm-v3.3.4-linux-amd64.tar.gz
* kind: v0.5.1
* kubectl: v1.5.2
* docker: version 19.03.9, build 9d988398e7

What is the correct usage?

**Comment by mmilenkoski** [comment]
Hi @b1ueshad0w, 

Thank you for reporting the issue! The third argument was removed. Could you please try `mlbench create-cluster kind 3 my-cluster`? 

Additionally, could you please tell us where did you find the command you are using? It is deprecated and should be removed from the documentation.

**Comment by b1ueshad0w** [comment]
I' ve updated the issue. Using only 2 arguments also fails.

**Comment by b1ueshad0w** [comment]
@ehoelzl  Any idea on this error?
```
# mlbench create-cluster kind 3 my-cluster
Creating cluster my-cluster-3
Usage: mlbench create-cluster kind [OPTIONS] num-workers RELEASE

Error: Failed to create cluster with the following error:
 Error: failed to create cluster: decoding failure: no kind "Cluster" is registered for version "kind.x-k8s.io/v1alpha4" in scheme "pkg/runtime/scheme.go:101"
```

**Comment by ehoelzl** [comment]
@b1ueshad0w Could you try updating kind to `v0.9.0` and kubectl to `v1.19.2`? I guess those are changes brought by the newer version we use:
```
curl -Lo ./kind "https://kind.sigs.k8s.io/dl/v0.9.0/kind-$(uname)-amd64"
chmod +x ./kind
mv ./kind /some-dir-in-your-PATH/kind
```

**Comment by b1ueshad0w** [comment]
@ehoelzl That seems work. I have another question. How can I run the mlbench among 2 (or more) existed VMs? The KIND solution uses only one VM.

**Comment by ehoelzl** [comment]
@b1ueshad0w you can specify the total number of nodes: `mlbench create-cluster kind <num-nodes> my-cluster`

**Comment by b1ueshad0w** [comment]
@ehoelzl By using the command with arg <num-nodes>, how does `mlbench create-cluster kind` know the ip address of the rest nodes(VMs)? I think at least a YAML file (or similar config) containing nodes' ip addresses is needed for mlbench&kind to construt the cluster.

**Comment by ehoelzl** [comment]
@b1ueshad0w What do you mean by "IP addresses of the rest of the nodes" ? KIND is made to be used on a local machine with docker.  All YAML configuration files are in the helm repository https://github.com/mlbench/mlbench-helm

**Comment by martinjaggi** [comment]
can we maybe clarify in our documentation that the `num-workers` (or num-nodes) in this case are all going to be running locally within the same docker?

**Comment by b1ueshad0w** [comment]
@martinjaggi Are you saying that it is not supported to run mlbench on 2 existed VMs (like EC2 instances) currently?

**Comment by ehoelzl** [comment]
@b1ueshad0w Could you please clarify what you are trying to do ?
MLBench supports the deployment on 3 platforms:
- Google Cloud
- AWS
- Local KIND cluster.

In each case, the cluster or instances are not already present and will be created by the CLI. Example:
`mlbench create-cluster kind 3 test` will create a kind cluster locally with 3 running nodes (each in a separate docker image) called `test-3`, and will deploy the dashboard on one of those nodes. The only required CLI command is the mentioned one.

The process is the same for GCloud and AWS. However, its is possible to deploy on an already existing cluster using `helm`. You just need to configure your `kubectl` client to communicate with the cluster.
