### ISSUE TITLE
math ValueError with 1-node cluster

### ISSUE THREAD

**Issue by giorgiosav** [mlbench/mlbench-core#38]
I did the following:
`mlbench create-cluster gcloud 1 my-cluster`

When I navigated to the Dashboard URL, I got a ValueError which I think is caused by max_workers being equal to zero in the expression `math.log2(max_workers)` (see stack trace and attached screenshots).

So this is probably not an urgent bug, but it might be good to error out immediately after running the command, if this is an invalid use.

Stack trace:
```
Traceback:
 
File "/venv/lib/python3.6/site-packages/django/core/handlers/exception.py" in inner
  35.             response = get_response(request)
 
File "/venv/lib/python3.6/site-packages/django/core/handlers/base.py" in _get_response
  128.                 response = self.process_exception_by_middleware(e, request)
 
File "/venv/lib/python3.6/site-packages/django/core/handlers/base.py" in _get_response
  126.                 response = wrapped_callback(request, *callback_args, **callback_kwargs)
 
File "./main/views.py" in runs
  39.         str(2 ** i) for i in range(0, math.floor(math.log2(max_workers)) + 1)
 
Exception Type: ValueError at /runs
Exception Value: math domain error
```
<img width="452" alt="Schermata 2020-03-09 alle 16 10 01" src="https://user-images.githubusercontent.com/28169576/76229426-76d06380-6222-11ea-944d-76496c4993e2.png">
<img width="800" alt="Schermata 2020-03-09 alle 16 19 10" src="https://user-images.githubusercontent.com/28169576/76229435-789a2700-6222-11ea-8bb2-4e0ce0ac50e9.png">

**Comment by Panaetius** [comment]
By design, you need at least #workers + 1 nodes (so the minimum is 2 nodes) to run something, as the dashboard/master runs on a separate node to not influence results. Maybe we should add 2 as the minimum for the cli creation?
