### ISSUE TITLE
Provide comparison to competitors

### ISSUE THREAD

**Issue by cgrigis** [mlbench/mlbench-core#66]
In order to highlight the unique features provided by mlBench, it would be very useful to document a list of competitor applications, and how they differ in their approach.

**Comment by martinjaggi** [comment]
yes let's definitely add that, including a section comparing to [MLperf](https://mlperf.org/)

**Comment by martinjaggi** [comment]
gdoc is in the works.

are we adding a webpage or documentation subsection/page for this?

**Comment by ehoelzl** [comment]
Closing in favor of https://github.com/mlbench/mlbench-docs/issues/46
