### ISSUE TITLE
Add notebook/code to visualize results

### ISSUE THREAD

**Issue by ehoelzl** [mlbench/mlbench-core#72]
It would be nice to have a code/notebook that takes care of generating the graphs for each benchmark task.

This way, all graphs would look the same, and it would be easier to post results on a blog-post/mlbench website

**Comment by Panaetius** [comment]
Ideally we'd include the graph in the downloaded zip file alongside the results.

**Comment by ehoelzl** [comment]
Closed in favor of https://github.com/mlbench/mlbench-results/issues/2
