### ISSUE TITLE
benchmark against torch.nn.parallel.DistributedDataParallel MPSG

### ISSUE THREAD

**Issue by martinjaggi** [mlbench/mlbench-core#75]
`torch.nn.parallel.DistributedDataParallel` was changed in pytorch 1.5 (see #74) https://github.com/pytorch/pytorch/releases/tag/v1.5.0

the purpose of this issue is to measure and document performance of our reference implementations compared to the `Multi-Process Single-GPU` (MPSG) mode of `DistributedDataParallel`

**Comment by ehoelzl** [comment]
Should we close this issue ? Or maybe open a new on the subject as the branch has been merged ?

**Comment by martinjaggi** [comment]
if i remember correctly this was measured by martin or giorgio, with pytorch 1.5. maybe the results could be pasted here so they don't get lost?

**Comment by ehoelzl** [comment]
Results are on the merge https://github.com/mlbench/mlbench-benchmarks/pull/42
