### ISSUE TITLE
Run new benchmarks and document costs

### ISSUE THREAD

**Issue by giorgiosav** [mlbench/mlbench-core#82]
It's still not very clear what kind of benchmarks we want to run, so I think we should list them here, e.g:
- [ ] CIFAR, light goal, GPU
- [ ] CIFAR, light goal, GPU
...

**Comment by martinjaggi** [comment]
there are many use-cases which need to be run
- the official task results (light and full goals need to run)
- scaling as part of official results
- comparing different hardware such as gcloud GPUs  K80,P100,P4,T4,V100 etc  
- GPU vs CPU (though official results will be GPU only)
- comparing backends (probably no scaling the # workers needed)
- comparing against pytorch DDP or powerSGD, or adam (again this is different than the official results so has different 
- regression testing compared to old versions of our code, and changes in pytorch, TF say
depending on what's needed for the scientific report (or blog post), that's what we'll run. ideally the code would be easy to adapt

**Comment by ehoelzl** [comment]
Superseded by https://github.com/mlbench/mlbench-benchmarks/issues/70
