### ISSUE TITLE
Support multiple clusters in CLI

### ISSUE THREAD

**Issue by giorgiosav** [mlbench/mlbench-core#91]
There doesn't seem to be a way to manage multiple clusters, e.g. if I want to create one cluster with GPUs and one without: it seems like all `mlbench` commands always refer to the most recently created cluster. It might be nice to have support for multiple clusters, each with its own dashboard.

**Comment by martinjaggi** [comment]
would be nice, but i would give it a bit lower priority at the moment (except if it's very easy to do without much code changes)
